config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'profiles/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  get 'notifications', to: 'notifications#index'
  get 'browse', to: 'posts#browse', as: :browse_posts
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def show
  end

  def edit
  end


  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

    def set_user
      @user = User.find_by(user_name: params[:user_name])
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle.avatar-image
                  = profile_avatar_select(@user)
                = f.file_field :avatar, label: false,
                                   input_html: { onChange: 'loadFile(event)' }
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4
          .form-group.text-center
            = f.button :submit,"Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button'
          - else
            = link_to 'Following', unfollow_user_path,
                                   remote: true,
                                   class: 'btn unfollow-button',
                                   id: 'unfollow-button',
                                   method: :post                            
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'
-@posts.each do |post|
  = render 'posts/post', post: post