config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'profiles/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  get 'notifications', to: 'notifications#index'
  get 'browse', to: 'posts#browse', as: :browse_posts
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post

    def index
    @comments = @post.comments.order('created_at asc')

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

    def create
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
          create_notificaton @post, @comment
          responds_to do |format|
            format.html {redirect_to root_path}
            format.js
          end
        else
          flash[:alert] = "Retry comment not saved"
          render root_path
        end
    end
    def destroy
      @comment = @post.comments.find(params[:id])

      if @comment.user_id == current_user.id
        @comment.delete
        respond_to do |format|
          format.html { redirect_to root_path }
          format.js
        end
      end
  end

 private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def create_notificaton(post)
      return if post.user.id == current_user.id
      Notification.create(user_id: post.user.id,
                          notified_by_id: current_user.id,
                          post_id: post.id,
                          comment_id: comment.id,
                          notice_type: 'comment')
                        end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    - if comment.user
      = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: {post_id: post.id, value: post.comments.count,  confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comment_content_<%= @post.id %>').val('')
$('#comment_content_<%= @post.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);

if (Append.comment || Append.open ){ $('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>"); }

else if ((Append.comment && Append.open) === false && Append.link === true) {
	$('#comments_' + Append.post_id).append("<div class='paginator' id='#comments-paginator-" + Append.post_id + "'><a class='more-comments' id='more_comments_" + Append.post_id + "' data-post-id='" + Append.post_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/posts/" + Append.post_id + "/comments'>view all " + Append.comment_count + " comments</a></div>");
	ClickableCommentsLink();
}

else if ((Append.comment && Append.open && Append.link) === false) { $('#more_comments_<%= @post.id %>').html("view all <%= @post.comments.count %> comments"); }

app/views/comments/destroy.js.erb
Append.comment_count -= 1$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
Append.comment_count -= 1

app/views/comments/index.html.haml
= render @comments, post: @post