config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'profiles/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  get 'notifications', to: 'notifications#index'
  get 'browse', to: 'posts#browse', as: :browse_posts
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true
end

app/views/notifications/_notification.html.haml
%li
  = link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification)

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-default.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': true }
    = current_user.notifications.count
    %span.glyphicon.glyphicon-flag
  %ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
    %li.dropdown-header.text-center Notifications
    = render current_user.notifications.order('created_at DESC').last(5)
    %li.divider{ role: 'separator' }
      %li.text-center= link_to 'View All', notifications_path

app/views/notifications/index.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %ul.notification-index-list
        = render @notifications

app/views/notifications/link_through.html.erb
<h1>Notificattions#link_through</h1>
<p>Find me in app/views/notificattions/link_through.html.erb</p>