config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'profiles/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  get 'notifications', to: 'notifications#index'
  get 'browse', to: 'posts#browse', as: :browse_posts
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
      acts_as_votable

      belongs_to :user
      has_many :comments,dependent: :destroy
      has_many :notifications, dependent: :destroy

      validates :image, presence: true
      validates :user_id, presence: true
      validates :caption, length: {minimum: 4, maximum: 200 }

      has_attached_file :image, styles: { medium: "640x640>", thumb: "100x100>" }
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
    before_action :owned_post, only: [:edit, :update, :destroy]
    def index
      @posts = Post.all.order('created_at DESC').page params[:page]
    end

    def show
    end

    def edit
    end

    def update
        if @post.update(post_params)
          flash[:success] = "Post updated."
          redirect_to root_path
        else
          flash.now[:alert] = "Update failed.  Please check the form."
          render  :edit
        end
    end

    def destroy
        @post.destroy
        flash[:success] = "Your post has been deleted."
        redirect_to posts_path
    end

    def like
      if @post.liked_by current_user
        respond_to do |format|
          format.html {redirect_to :back}
          format.js
        end
      end
    end

    def new
        @post = current_user.posts.build
    end


    def create
        @post = current_user.posts.build(post_params)
        if @post.save
          flash[:success] = "Your post has been created!"
          redirect_to  root_path
        else
           flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
          render :new
        end
    end

    private
    def post_params
      params.require(:post).permit(:image, :caption)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def owned_post
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you !!!"
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end 

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        =link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        =time_ago_in_words post.created_at
    .image.center-block
      =link_to (image_tag post.image.url(:medium), class:'img-responsive'),
                 post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            =link_to post.user.user_name, profile_path(post.user.user_name)
          =post.caption
          .comments{id: "comments_#{post.id}"}
            -if post.comments.any?
              = render post.comments.first(4), post: post
              -unless post.comments.count <= 4
                .paginator{id: "#comments-paginator-#{post.id}"}
                  =link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"}
    .comment-like-form.row
      .col-sm-1.like-button
        =link_to '', like_post_path(post.id), remote: true,
                                              id: "like_#{post.id}",
                                              class: "like glyphicon #{liked_post post}"
      .comment-form.col-sm-11
        =form_for([post, post.comments.build], remote: true) do |f|
          =f.text_field :content, placeholder: 'Add a comment...',
                                   class: "comment_content",
                                   id: "comment_content_#{post.id}",
                                   data: { post_id: "#{post.id}",
                                   value: "#{post.comments.count}" }
          =f.submit 'New Comment', class: 'comment-submit-button'

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", posts_path

app/views/posts/index.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post
- if @post.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
- else
  .text-center.edit-links
    =link_to "Cancel", posts_path